= Guided solution (page 1)

== Objectives
* Investigate the instance connectivity issue in Red Hat OpenStack Services on OpenShift.
* Solve the instance connectivity in the hands-on lab environment.

== Outcomes
* Investigate why ssh to instance through the forwarded port is not working.
* Fix the ssh to instance failing issue.

== Instructions

1. Break the environment if you have not done it and then step through the fix.
+
----
[student@workstation ~]$ lab start bfx027
Running start action against scenario bfx027
Run the following command:
ssh -p 1022 -i /tmp/scenario-bfx027-key.pem cirros@192.168.51.165
----

2. Run the ssh command from the previous lab command output and notice the Connection timed out error.
+
----
[student@workstation ~]$ ssh -p 1022 -i /tmp/scenario-bfx027-key.pem cirros@192.168.51.165
ssh: connect to host 192.168.51.165 port 1022: Connection timed out
----
+
You observe that ssh attempt failed which indicates lack of connectivity using configured port forwarding.
There is only port forwarding for the TCP port 1022 to port 22 configured, thus the ping command will not work and that is an expected behaviour.

3. Check connectivity to the other VM with Floating IP configured
+
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack server list
+--------------------------------------+------------------------+--------+---------------------------------------------------------+---------------------+----------+
| ID                                   | Name                   | Status | Networks                                                | Image               | Flavor   |
+--------------------------------------+------------------------+--------+---------------------------------------------------------+---------------------+----------+
| a8a05113-822a-4b60-9198-8f89f1e05cdc | scenario-bfx027-pf-vm  | ACTIVE | scenario-bfx027-network=192.168.200.139                 | cirros-0.5.2-x86_64 | m1.small |
| e4f8e03e-8d13-4410-bf7f-52e481179e1e | scenario-bfx027-fip-vm | ACTIVE | scenario-bfx027-network=192.168.200.224, 192.168.51.180 | cirros-0.5.2-x86_64 | m1.small |
+--------------------------------------+------------------------+--------+---------------------------------------------------------+---------------------+----------+

[student@workstation ~]$ ssh -i /tmp/scenario-bfx027-key.pem cirros@192.168.51.180
Warning: Permanently added '192.168.51.180' (ECDSA) to the list of known hosts.
$ cat /etc/cirros/version
0.5.2
----
+
Connectivity to other VM using Floating IP works fine which indicates that the issue is not with the connectivity in general but rather that there is some issue with Floating IP Port Forwarding.

4. Floating IP Port Forwardings created in the Neutron are translated to the Loadbalancer in OVN. First lets check if such loadbalancer was created in OVN.
+
----
[student@workstation ~]$ oc exec -n openstack $(oc get pods -n openstack -l service=ovsdbserver-nb -o name | head -n 1) -- ovn-nbctl --no-leader-only list load_balancer
_uuid               : 3f931dab-2f58-41f3-bcf5-48b17b091ccb
external_ids        : {"neutron:device_owner"=port_forwarding_plugin, "neutron:fip_id"="be9f3c09-7edb-41d7-8172-311cda772f29", "neutron:revision_number"="2", "neutron:router_name"=neutron-1f8305ff-682d-4bd7-9c92-59a2197bb83a}
health_check        : []
ip_port_mappings    : {}
name                : pf-floatingip-be9f3c09-7edb-41d7-8172-311cda772f29-tcp
options             : {}
protocol            : tcp
selection_fields    : []
vips                : {"192.168.51.165:1022"="192.168.200.139:22"}
----
+
Loadbalancer seems to be created properly in OVN.
Important thing to know is that loadbalancers in OVN are always centralized, which means that traffic using Floating IP Port Forwarding is always going through the gateway chassis where the router is hosted.

5. Determine which gateway-chassis is your router on.
+
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack router show scenario-bfx027-router -c id
+-------+--------------------------------------+
| Field | Value                                |
+-------+--------------------------------------+
| id    | 1f8305ff-682d-4bd7-9c92-59a2197bb83a |
+-------+--------------------------------------+

[student@workstation ~]$ oc exec -n openstack $(oc get pods -n openstack -l service=ovsdbserver-nb -o name | head -n 1) -- ovn-nbctl --no-leader-only show neutron-b9968cde-1f94-43a4-a537-23bef2682920
router 3584d841-f037-4f8d-a0bd-34ff9fd7cbe6 (neutron-1f8305ff-682d-4bd7-9c92-59a2197bb83a) (aka scenario-bfx027-router)
    port lrp-1c9df04d-55fd-4eaa-a0e6-7445a363324d
        mac: "fa:16:3e:43:78:21"
        networks: ["192.168.51.179/24"]
        gateway chassis: [5a3b4e75-f64a-4261-bfb9-290d09f259e4 bfbef098-d0f7-4f26-a5e0-aa89c079ca15 1048012a-c14c-4354-93e3-837701980ce3]
    port lrp-fb802392-c9ec-4b3e-925b-1ce7176d8dde
        mac: "fa:16:3e:fc:03:62"
        networks: ["192.168.200.1/24"]
    nat be9f0cc7-c806-408f-9eac-9a3ae3382900
        external ip: "192.168.51.179"
        logical ip: "192.168.200.0/24"
        type: "snat"
    nat c04bdb2b-c53c-4567-b647-7ab3f974b2ea
        external ip: "192.168.51.180"
        logical ip: "192.168.200.224"
        type: "dnat_and_snat"

[student@workstation ~]$ oc exec -n openstack $(oc get pods -n openstack -l service=ovsdbserver-nb -o name | head -n 1) -- ovn-nbctl --no-leader-only lrp-get-gateway-chassis lrp-d49dbb2a-eba9-49c2-9723-5c9d4adcdad7
lrp-1c9df04d-55fd-4eaa-a0e6-7445a363324d_bfbef098-d0f7-4f26-a5e0-aa89c079ca15     3
lrp-1c9df04d-55fd-4eaa-a0e6-7445a363324d_1048012a-c14c-4354-93e3-837701980ce3     2
lrp-1c9df04d-55fd-4eaa-a0e6-7445a363324d_5a3b4e75-f64a-4261-bfb9-290d09f259e4     1

[student@workstation ~]$ oc exec -n openstack $(oc get pods -n openstack -l service=ovsdbserver-sb -o name | head -n 1) -- ovn-sbctl --no-leader-only list chassis bfbef098-d0f7-4f26-a5e0-aa89c079ca15
_uuid               : 5ac0d497-f5a3-463f-8029-7f815f017f65
encaps              : [7bc632b2-a61d-4f4d-8cce-067b56e48255]
external_ids        : {}
hostname            : master03
name                : "bfbef098-d0f7-4f26-a5e0-aa89c079ca15"
nb_cfg              : 0
other_config        : {ct-commit-nat-v2="true", ct-commit-to-zone="true", ct-no-masked-label="true", datapath-type=system, fdb-timestamp="true", iface-types="bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,srv6,stt,system,tap,vxlan", is-interconn="false", ls-dpg-column="true", mac-binding-timestamp="true", ovn-bridge-mappings="datacentre:br-datacentre", ovn-chassis-mac-mappings="", ovn-cms-options=enable-chassis-as-gw, ovn-ct-lb-related="true", ovn-enable-lflow-cache="true", ovn-limit-lflow-cache="", ovn-memlimit-lflow-cache-kb="", ovn-monitor-all="false", ovn-trim-limit-lflow-cache="", ovn-trim-timeout-ms="", ovn-trim-wmark-perc-lflow-cache="", port-up-notif="true"}
transport_zones     : []
vtep_logical_switches: []
----
+
Your router is hosted on 3 gateway chassis and the one which is active now is on the OpenShift node `master03`.

6. Determine which OVS POD runs on that OpenShift worker node.
+
----
[student@workstation ~]$ oc get pods -n openstack -l service=ovn-controller-ovs -o custom-columns=NAME:.metadata.name,NODE:spec.nodeName
NAME                       NODE
ovn-controller-ovs-96x87   master02
ovn-controller-ovs-hp8bm   master03
ovn-controller-ovs-htgrl   master01
----
+
In our case it is the POD `ovn-controller-ovs-hp8bm`.

7. Check what is the network type and physnet used by this network
+
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack network show scenario-bfx027-network
+---------------------------+--------------------------------------+
| Field                     | Value                                |
+---------------------------+--------------------------------------+
...
| name                      | scenario-bfx027-network              |
...
| provider:network_type     | vlan                                 |
| provider:physical_network | datacentre                           |
| provider:segmentation_id  | 1000                                 |
...
+---------------------------+--------------------------------------+
----
+
In this case network used by the instances is provider `vlan` network and it uses `datacentre` physical network.
Gateway chassis are hosted by the ovn-controller running in the POD on the OpenShift worker nodes, this physical network has to be configured in the `nicMapping` parameter in the `OpenStackControlPlane` Custom Resource in OpenShift.
+
8. Check NIC mappings configured in the OpenStackControlPlane Custom Resource.
+
----
[student@workstation ~]$ oc -n openstack get openstackcontrolplane openstack-control-plane -o custom-columns=NAME:.metadata.name,"NIC MAPPINGS":.spec.ovn.template.ovnController.nicMappings
NAME                      NIC MAPPINGS
openstack-control-plane   map[datacentre:ens4]
----
In this case physical network `datacentre` is mapped to the `ens4` NIC which is on the OpenShift worker nodes. This `ens4` NIC is moved directly to the `ovn-controller-ovs` POD and it has name the same as physical network it is mapped to. In our case interface found in the `ovn-controller-ovs` POD should have name `datacentre` and the bridge created for that physical network is named `br-datacentre`.
+
9. Check traffic on the gateway chassis node hosting Neutron router.
+
Run tcpdump in the OVS POD to check traffic incomming to that POD through the `datacentre` NIC and in different window run SSH connection from the `workstation` machine to the TCP port 1022, as shown in the instruction after scenario was started.
+
----
[student@workstation ~]$ oc rsh -n openstack -c ovs-vswitchd ovn-controller-ovs-hp8bm
sh-5.1# tcpdump -ennvvi datacentre
dropped privs to tcpdump
tcpdump: listening on datacentre, link-type EN10MB (Ethernet), snapshot length 262144 bytes
10:30:36.348303 52:54:00:02:33:fe > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 74: (tos 0x48, ttl 63, id 27712, offset 0, flags [DF], proto TCP (6), length 60)
    172.25.250.9.36684 > 192.168.51.165.1022: Flags [S], cksum 0x7a85 (correct), seq 2873327163, win 32120, options [mss 1460,sackOK,TS val 3460573827 ecr 0,nop,wscale 7], length 0
10:30:36.349555 fa:16:3e:fc:03:62 > fa:16:3e:d1:be:35, ethertype 802.1Q (0x8100), length 78: vlan 1000, p 0, ethertype IPv4 (0x0800), (tos 0x48, ttl 62, id 27712, offset 0, flags [DF], proto TCP (6), length 60)
    172.25.250.9.36684 > 192.168.200.139.22: Flags [S], cksum 0xe986 (correct), seq 2873327163, win 32120, options [mss 1460,sackOK,TS val 3460573827 ecr 0,nop,wscale 7], length 0
10:30:36.357722 1e:0a:ab:52:a1:d7 > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 74: (tos 0x10, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.200.139.22 > 172.25.250.9.36684: Flags [S.], cksum 0x83d7 (correct), seq 2074550143, ack 2873327164, win 65160, options [mss 1460,sackOK,TS val 3230007 ecr 3460573827,nop,wscale 6], length 0
10:30:36.358831 fa:16:3e:43:78:21 > 52:54:00:02:33:fe, ethertype IPv4 (0x0800), length 74: (tos 0x10, ttl 62, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.51.165.1022 > 172.25.250.9.36684: Flags [S.], cksum 0x14d6 (correct), seq 2074550143, ack 2873327164, win 65160, options [mss 1460,sackOK,TS val 3230007 ecr 3460573827,nop,wscale 6], length 0
10:30:36.359681 52:54:00:02:33:fe > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 66: (tos 0x48, ttl 63, id 27713, offset 0, flags [DF], proto TCP (6), length 52)
    172.25.250.9.36684 > 192.168.51.165.1022: Flags [.], cksum 0x9a97 (incorrect -> 0x4123), seq 1, ack 1, win 251, options [nop,nop,TS val 3460573839 ecr 3230007], length 0
10:30:36.360322 52:54:00:02:33:fe > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 87: (tos 0x48, ttl 63, id 27714, offset 0, flags [DF], proto TCP (6), length 73)
    172.25.250.9.36684 > 192.168.51.165.1022: Flags [P.], cksum 0x9aac (incorrect -> 0x795c), seq 1:22, ack 1, win 251, options [nop,nop,TS val 3460573840 ecr 3230007], length 21
10:30:36.572681 52:54:00:02:33:fe > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 87: (tos 0x48, ttl 63, id 27715, offset 0, flags [DF], proto TCP (6), length 73)
    172.25.250.9.36684 > 192.168.51.165.1022: Flags [P.], cksum 0x9aac (incorrect -> 0x7888), seq 1:22, ack 1, win 251, options [nop,nop,TS val 3460574052 ecr 3230007], length 21
10:30:36.788717 52:54:00:02:33:fe > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 87: (tos 0x48, ttl 63, id 27716, offset 0, flags [DF], proto TCP (6), length 73)
    172.25.250.9.36684 > 192.168.51.165.1022: Flags [P.], cksum 0x9aac (incorrect -> 0x77b0), seq 1:22, ack 1, win 251, options [nop,nop,TS val 3460574268 ecr 3230007], length 21
10:30:37.220719 52:54:00:02:33:fe > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 87: (tos 0x48, ttl 63, id 27717, offset 0, flags [DF], proto TCP (6), length 73)
    172.25.250.9.36684 > 192.168.51.165.1022: Flags [P.], cksum 0x9aac (incorrect -> 0x7600), seq 1:22, ack 1, win 251, options [nop,nop,TS val 3460574700 ecr 3230007], length 21
10:30:37.367140 1e:0a:ab:52:a1:d7 > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 74: (tos 0x10, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.200.139.22 > 172.25.250.9.36684: Flags [S.], cksum 0x2f86 (incorrect -> 0x7fe5), seq 2074550143, ack 2873327164, win 65160, options [mss 1460,sackOK,TS val 3231017 ecr 3460573827,nop,wscale 6], length 0
10:30:37.367161 fa:16:3e:43:78:21 > 52:54:00:02:33:fe, ethertype IPv4 (0x0800), length 74: (tos 0x10, ttl 62, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.51.165.1022 > 172.25.250.9.36684: Flags [S.], cksum 0x9a9f (incorrect -> 0x10e4), seq 2074550143, ack 2873327164, win 65160, options [mss 1460,sackOK,TS val 3231017 ecr 3460573827,nop,wscale 6], length 0
10:30:37.367627 52:54:00:02:33:fe > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 66: (tos 0x48, ttl 63, id 27718, offset 0, flags [DF], proto TCP (6), length 52)
    172.25.250.9.36684 > 192.168.51.165.1022: Flags [.], cksum 0x9a97 (incorrect -> 0x3d1e), seq 22, ack 1, win 251, options [nop,nop,TS val 3460574847 ecr 3230007], length 0
10:30:38.092714 52:54:00:02:33:fe > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 87: (tos 0x48, ttl 63, id 27719, offset 0, flags [DF], proto TCP (6), length 73)
    172.25.250.9.36684 > 192.168.51.165.1022: Flags [P.], cksum 0x9aac (incorrect -> 0x7298), seq 1:22, ack 1, win 251, options [nop,nop,TS val 3460575572 ecr 3230007], length 21
^C
13 packets captured
13 packets received by filter
0 packets dropped by kernel
----
+
You can observe that there are incomming packets going to the TCP port 1022. Those packets are not tagged with any vlan id - those are packets going from the workstation server using `public` network.
There are also packets sent to the TCP port 22 to the fixed IP of the VM (`192.168.200.139`). Those packets are tagged with vlan ID 1000 which match the ID configured in the `provider:segmentation_id` of the the `scenario-bfx027-network` network. Those are packets send from the Neutron router to the VM and should be observed on the compute node where VM is running.

10. Access the RHOSO environment and determine the specific compute node where the instance is currently running.
+
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack server list --long -c Name -c Status -c Host
+------------------------+--------+---------------------------+
| Name                   | Status | Host                      |
+------------------------+--------+---------------------------+
| scenario-bfx027-pf-vm  | ACTIVE | compute02.srv.example.com |
| scenario-bfx027-fip-vm | ACTIVE | compute01.srv.example.com |
+------------------------+--------+---------------------------+
----
+
Observe that it is compute02 in the above output, it my differ in your case.

11. Access the compute02 node and identify NIC connected to the `datacentre` physnet.
+
----
[student@workstation ~]$ ssh root@compute02.srv.example.com
Warning: Permanently added 'utility' (ED25519) to the list of known hosts.
Warning: Permanently added 'compute02.srv.example.com' (ED25519) to the list of known hosts.
Activate the web console with: systemctl enable --now cockpit.socket

Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Mon Apr  7 12:31:28 2025 from 192.168.51.254

[root@compute02 ~]# ovs-vsctl list Open .
...
external_ids        : {..., ovn-bridge-mappings="datacentre:br-ex", ovn-chassis-mac-mappings="datacentre:1e:0a:ab:52:a1:d7", ...}
...

[root@compute02 ~]# ovs-vsctl show
426daad2-29a0-47a0-b829-638852d1dfd6
    Manager "ptcp:6640:127.0.0.1"
        is_connected: true
    Bridge br-ex
        fail_mode: standalone
        Port patch-provnet-d8d5f080-4af9-4f09-8f10-72c320c99f78-to-br-int
            Interface patch-provnet-d8d5f080-4af9-4f09-8f10-72c320c99f78-to-br-int
                type: patch
                options: {peer=patch-br-int-to-provnet-d8d5f080-4af9-4f09-8f10-72c320c99f78}
        Port br-ex
            Interface br-ex
                type: internal
        Port patch-provnet-9c93546f-0f08-407b-9d65-e38b3d616746-to-br-int
            Interface patch-provnet-9c93546f-0f08-407b-9d65-e38b3d616746-to-br-int
                type: patch
                options: {peer=patch-br-int-to-provnet-9c93546f-0f08-407b-9d65-e38b3d616746}
        Port eth2
            Interface eth2
----
+
The above output shows that the route goes through eth2.

12. Run tcpdump on the eth2 interface to check traffic incoming to that node and in different window run SSH connection from the `workstation` machine to the TCP port 1022, as shown in the instruction after scenario was started.
+
----
[root@compute02 ~]# tcpdump -ennvvi eth2 host 192.168.200.139
dropped privs to tcpdump
tcpdump: listening on eth2, link-type EN10MB (Ethernet), snapshot length 262144 bytes
14:34:52.571214 fa:16:3e:fc:03:62 > fa:16:3e:d1:be:35, ethertype 802.1Q (0x8100), length 78: vlan 1000, p 0, ethertype IPv4 (0x0800), (tos 0x48, ttl 62, id 35962, offset 0, flags [DF], proto TCP (6), length 60)
    172.25.250.9.51964 > 192.168.200.139.22: Flags [S], cksum 0x0f95 (correct), seq 896855695, win 32120, options [mss 1460,sackOK,TS val 3475230048 ecr 0,nop,wscale 7], length 0
14:34:52.572584 1e:0a:ab:52:a1:d7 > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 74: (tos 0x10, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.200.139.22 > 172.25.250.9.51964: Flags [S.], cksum 0x86e3 (correct), seq 2780525712, ack 896855696, win 65160, options [mss 1460,sackOK,TS val 17886260 ecr 3475230048,nop,wscale 6], length 0
14:34:53.584992 1e:0a:ab:52:a1:d7 > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 74: (tos 0x10, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.200.139.22 > 172.25.250.9.51964: Flags [S.], cksum 0x2f86 (incorrect -> 0x82ee), seq 2780525712, ack 896855696, win 65160, options [mss 1460,sackOK,TS val 17887273 ecr 3475230048,nop,wscale 6], length 0
14:34:55.600994 1e:0a:ab:52:a1:d7 > fa:16:3e:43:78:21, ethertype IPv4 (0x0800), length 74: (tos 0x10, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.200.139.22 > 172.25.250.9.51964: Flags [S.], cksum 0x2f86 (incorrect -> 0x7b0e), seq 2780525712, ack 896855696, win 65160, options [mss 1460,sackOK,TS val 17889289 ecr 3475230048,nop,wscale 6], length 0
^C
4 packets captured
4 packets received by filter
0 packets dropped by kernel
----
+
Packets are coming to the compute node with correct vlan ID 1000, which matches the segmentation id set for the tenant network in the Neutron but the response from the VM is going out without any vlan ID tag. This means they it is send out directly using the flat `public` network created in the Neutron.

13. Check Logical Router Port of the `tenant` network connected to the router
+
----
[student@workstation scenarios_repo]$ oc exec -n openstack $(oc get pods -n openstack -l service=ovsdbserver-nb -o name) -- ovn-nbctl --no-leader-only list logical_router_port
...
_uuid               : 970d91eb-6ca8-40ce-aea0-9bb0ba75b787
enabled             : []
external_ids        : {"neutron:is_ext_gw"=False, "neutron:network_name"=neutron-d6409377-d4a6-45ba-b551-1991ca178072, "neutron:revision_number"="2", "neutron:router_name"="1f8305ff-682d-4bd7-9c92-59a2197bb83a", "neutron:subnet_ids"="91a29fe7-ea8f-4ae5-aa93-c22beeb5d8e1"}
gateway_chassis     : []
ha_chassis_group    : []
ipv6_prefix         : []
ipv6_ra_configs     : {}
mac                 : "fa:16:3e:fc:03:62"
name                : lrp-fb802392-c9ec-4b3e-925b-1ce7176d8dde
networks            : ["192.168.200.1/24"]
options             : {reside-on-redirect-chassis="false"}
peer                : []
status              : {}
----
+
This Logical Router Port has set option `reside-on-redirect-chassis` to `false` which, according to the OVN documentation means one of the following:
[quote]
traffic goes tunneled to the controller with the gateway port
+
or
[quote]
with ovn-chassis-mac-mappings configured: means the traffic is fully distributed and it is not being tunneled, nor sent, through the controller with the gateway port.
+
In this case it is the latter because `ovn-chassis-mac-bindings` is set in the `external_ids` on the node - see point 11.
