= What’s in this break-fix?

== In this break-fix:

**Type of issue:**

Your team manages a Red Hat OpenStack Platform (RHOSP) infrastructure used by an important development team for your company. There was a requirement from your internal networking team to have Open Virtual Network (OVN), an open-source software-defined networking (SDN) solution that seamlessly integrates with OpenStack. Recently networking team noticed that there is connectivity issue with instance running in OpenStack envrionment.

They noticed the following error when they try to connect to the instance:
----
[student@workstation scenarios_repo]$ ssh -p 1022 -i /tmp/scenario-bfx027-key.pem cirros@192.168.51.97
kex_exchange_identification: read: Connection reset by peer
Connection reset by 192.168.51.97 port 1022
----

**How break-fix training works:**

. Challenge yourself in the break-fix activity. It describes a problem scenario that's simulated in the lab environment where you can investigate and solve the problem.
. Follow up with the guided solution:
.. If you weren't able to solve the problem on your own, read and follow the instructions in the Guided Solution to complete this training.
.. If you were successful in solving the problem, read the solution for useful tips you can apply when solving similar problems.
