= Check your work

== Check your work using the grading script:
----
[student@workstation ~]$ lab grade bfx027
Running grade action against scenario bfx027
Grading scenario bfx027: PASSED!
----
Instance IP address from the preceding output can differ in your environment.
[NOTE]
====
If the ssh connection to the guest requires a password, the default for Cirros
images is "gocubsgo".
====
== Success Criteria
Successful completion of this activity requires that ssh to the instance is working:
----
[student@workstation ~]$ ssh -p 1022 -i /tmp/scenario-bfx027-key.pem cirros@192.168.51.97
$
----

[NOTE]
====
We recommend treating these scenarios as challenges first and attempting to resolve them independently. Even if you successfully resolve the issue on your own, it is valuable to go through the guided steps to understand the approach demonstrated in this training. Note that the MAC addresses, IP addresses, and other details referenced in the guided steps might vary in your specific scenario.
