= Break-fix Scenario

Objectives:

* Investigate the instance connectivity issue in Red Hat OpenStack Services on OpenShift.

* Solve the instance connectivity in the hands-on lab environment.

Scenario:

Your team manages a Red Hat OpenStack Services on OpenShift (RHOSO) infrastructure used by an important development team for your company. There was a requirement from your internal networking team to have Open Virtual Network (OVN), an open-source software-defined networking (SDN) solution that seamlessly integrates with OpenStack. Recently networking team noticed that there is Floating IP Port Forwarding connectivity issue with instance running in OpenStack environment.

They noticed the following error:

----
[student@workstation scenarios_repo]$ ssh -p 1022 -i /tmp/scenario-bfx027-key.pem cirros@192.168.51.97
kex_exchange_identification: read: Connection reset by peer
Connection reset by 192.168.51.97 port 1022
----


== Recreate scenario

. Log in to your lab environment on the **ROLE** platform.
. As the **student** user, run the lab start script on the **workstation** VM to reproduce the issue.
+
[source, bash]
----
cd /home/student/osp_training/scenarios_repo/
./lab start bfx027
----
+
The lab customization script is already cloned in the **/home/student/osp_training/scenarios_repo/** directory.
+
.Sample output
----
[student@workstation ~]$ cd /home/student/osp_training/scenarios_repo/
[student@workstation scenarios_repo]$ ./lab start bfx027
Run the following command: 
ssh -p 1022 -i /tmp/scenario-bfx027-key.pem cirros@192.168.51.97
----
+
In the preceding output, IP address can differ in your lab environment.

. This creates an instance with broken ssh connectivity.
. To ensure scenario is recreated, run the ssh command from the previous output:
+
.Sample output
----
[student@workstation scenarios_repo]$ ssh -p 1022 -i /tmp/scenario-bfx027-key.pem cirros@192.168.51.97
kex_exchange_identification: read: Connection reset by peer
Connection reset by 192.168.51.97 port 1022
----

**IMPORTANT NOTE:** 

* If the lab script fails, you will not see the ssh command for instance connectivity.
* Wait a few minutes for the lab to initialize properly, then re-run the lab start script.
* You can retrieve the instance connectivity message generated by the lab script at any time by running the following command.
+
[source, bash]
----
cat ~/osp_training/.scenariobfx019/message
----

* Run the lab finish script if you wish to clean up the environment either to start fresh or to switch to another scenario.
+
[source, bash]
----
cd /home/student/osp_training/scenarios_repo/
./lab finish bfx027
----